### PR TITLE
Added libssl-dev (not installed on rpi's), otherwise the additional python lib will not build

### PR DESCRIPTION
**Pull request by ThaStealth**

### CODE REVIEW

**Comment by dominicmcglinn** [comment]
confirmed this fixed my build error

**Comment by GsynthChris** [comment]
Hello, You may want to add this in the mix.

When running the new prereq script (with libssl-dev added on the list) I was met with `' error: command 'x86_64-linux-gnu-gcc' failed with exit status 1 '`

To correct that I ran:
```
sudo apt-get install python3 python-dev python3-dev \
     build-essential libssl-dev libffi-dev \
     libxml2-dev libxslt1-dev zlib1g-dev \
     python-pip
```

After that I ran the prereq script again and was able to get sslpsk installed and the rest was a breeze!


Did you ever know that you're my hero?!?!?!?! ;-)

**Comment by jkuehl2** [comment]
finally works with this PR on my raspi4

**Comment by henry2man** [comment]
Please merge this on master. This also worked for me 

> sudo apt-get install python3 python-dev python3-dev \
>      build-essential libssl-dev libffi-dev \
>      libxml2-dev libxslt1-dev zlib1g-dev \
>      python-pip

**Comment by kueblc** [comment]
This fork is outdated, please see the main project which has these changes and more

**Comment by henry2man** [comment]
> This fork is outdated, please see the main project which has these changes and more

Thanks for pointing me. I was following this tutorial: https://domoticaencasa.es/tutorial-cambiar-firmware-a-los-dispositivos-tuya-smart-life-sin-soldar/

**Pull request closed without merging**
